name: umkm_connect
description: "An UMKM management apps."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  carousel_slider: ^5.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_cart: ^0.0.9
  flutter_login: ^5.0.0
  flutter_secure_storage: ^9.2.4
  http: ^1.4.0
  image_picker: ^1.1.2
  infinite_scroll_pagination: ^5.0.0
  intl: ^0.20.2
  path: ^1.9.1
  shared_preferences: ^2.5.3
  video_player: ^2.10.0
  webview_flutter: ^4.13.0
  youtube_player_flutter: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/banner1.jpg
    - assets/banner2.jpg
    - assets/banner3.jpg
